import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar2 from "@/components/Navbar2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Just a Login Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="min-h-screen flex flex-col justify-stretch bg-gray-100">
          {/* <MyNavbar /> */}
          <NavBar2 />
          {children}
        </main>
      </body>
    </html>
  );
}
